services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    domainname: voresid.com
    hostname: ha.voresid.com
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - ./homeassistant:/config
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      # Only add if you have Zigbee/Z-Wave USB sticks â€” adjust path as needed
      # - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - proxy
    labels:
      - "tra chills.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.voresid.com`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=myresolver"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
